services:
  api:
    build:
      context: .
    container_name: adopet-api
    ports:
      - 9000:9000
    volumes:
      - .:/usr/src/api
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:8
    container_name: adopet-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    user: root
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
