services:
  api:
    build:
      context: .
      target: dev
    container_name: adopet-api
    ports:
      - 9000:9000
    environment:
      NODE_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: null
      MYSQL_DB: adopet_dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/api/
  
  db:
    image: mysql:8
    container_name: adopet-db
    restart: always
    user: root
    secrets:
      - db-root-password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db-root-password
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

secrets:
  db-root-password:
    file: db/password.txt