version: '3.4'

services:
  dev:
    build:
      context: .
      target: dev
    container_name: adopet-api-dev
    command: npm run dev
    working_dir: /app
    ports:
      - 9000:9000
    environment:
      NODE_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: adopet_dev
      POSTGRES_HOST: db
    volumes:
      - ./:/app:cached
    depends_on:
      db:
        condition: service_healthy

  test:
    build:
      context: .
      target: dev
    container_name: adopet-api-tst
    command: npm run test
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - ./:/app:cached
  
  db:
    image: postgres
    container_name: adopet-db
    ports:
      - 5433:5432
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adopet_dev
      POSTGRES_PASSWORD: secret
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:
