name: build

on:
    pull_request: 
      branches: [ "main" ]
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v3.2.0

            - name: Build and push Docker images
              uses: docker/build-push-action@v5.3.0
              with:
                context: .
                push: true
                target: prod
                tags: ${{ secrets.DOCKER_USERNAME }}/adopet-api:latest
          